### ISSUE TITLE
Wrong highlighting for inline JS objects

### ISSUE THREAD

**Issue by grassator** [skozlovf/Sublime-QML#3]
Sample code:

``` qml
QtObject {
    property var test: { sdf: "sdfs", sdfg: "sdfsd" }
}
```

Screenshot:
![screen shot 2014-03-12 at 20 26 14](https://f.cloud.github.com/assets/317518/2397388/eabd3dec-a9e9-11e3-881f-dc44ece97251.png)

**Comment by ratijas** [comment]
This is invalid QML syntax. Object literal in a binding position without (parenthesis) will be parsed as a code block. Thus, `sdf` becomes a label (for `goto`), `"sdfs", sdfg` is an expression with binary comma operator (which evaluates and discards left-hand-side value), and after that is an unparsable mess (colon `:`).

Anyway, proper JavaScript code blocks and expressions are implemented in https://github.com/ratijas/Sublime-QML/commit/89b0fa880a947300b35742377ece69460a9d89a2
