### ISSUE TITLE
Broken highlighting on Sublime Text 3 Build 3103

### ISSUE THREAD

**Issue by putte** [skozlovf/Sublime-QML#6]
After upgrading sublime text 3 some of the syntax highlighting is not working as expected.

**Comment by skozlovf** [comment]
Hm, I'll check.

**Comment by skozlovf** [comment]
It's a sublime text 3 bug.
https://forum.sublimetext.com/t/syntax-not-working-anymore/17531

**Comment by skozlovf** [comment]
Works again in build 3126
